version: "3.9"
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    networks:
      - users_task_myNetwork
  api_admins:
    build:
      context: ./
      target: base
    volumes:
      - .:/src
    command: npm run start
    ports:
      - ${APP_PORT}:${APP_PORT}
    environment:
      NODE_ENV: development
      DEBUG: nodejs-docker-express:*
      DB_HOST: localhost
      DB_PORT: 5432
      DB_USERNAME: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
      APP_PORT: 3010
      JWT_SECRET: ${JWT_SECRET}
      ACCESS_TOKEN_SECRET: ${ACCESS_TOKEN_SECRET}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
volumes:
  postgres_data:
networks:
  users_task_myNetwork:
    external: true


